refactoring main page and component - mobile first
js-tasks-ru/htmlcss-20210812_vadim992 pull request #13
Opened 2021-09-05 15:34 UTC by vadimkozin

Было сказано на лекции - "Пожалуй это самое простое задание кроме первого..."  Ничего подобного. Я с трудом писал CSS - чтобы хорошо было и для мобильных и для десктопа. Зато потом можно было отдохнуть на иконках.

1) Сверстал мобильную версию главной страницы и страницы компонента
2) Сделал svg-sprite с набором иконок для сайта
3) Применил эти иконки в Аккордеоне, модальном окне, тултипе

Можно проверять.

2021-09-05 15:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-06 12:05 UTC, GSemikozov requested changes

2021-09-06 12:05 UTC, GSemikozov commented on components/card/card.css
> +  height: 232px;
здесь и везде ниже - указывать высоту карточки не обязательно, она должна определяться внутренним содержимым)

2021-09-06 12:05 UTC, GSemikozov commented on components/page/page.css
> +    max-width: 90%;
чтобы не писать 90% или 96% (а сделано это насколько я понимаю чтобы контент на прилипал к краям окна браузера) - можно просто задать паддинги (например, 16px по краям), и тогда отступы слева и справа всегда будут одинаковыми и предсказуемыми

2021-09-07 15:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-07 15:37 UTC, vadimkozin commented on components/card/card.css
> +  height: 232px;
Высоту заменил на min-height. Содержимого еще нет, и если совсем не указать высоту - то карточка схлопывается.

2021-09-07 15:41 UTC, vadimkozin commented on components/page/page.css
> +    max-width: 90%;
Заменил на width: calc(100% - 8px); и calc(100% - 16px); в разных брейкпоинтах.

2021-09-07 15:41 UTC, vadimkozin commented
Всё поправил. Можно проверять.

2021-09-07 18:08 UTC, GSemikozov approved these changes

2021-09-07 18:08 UTC, merged