added dz7-checkbox
js-tasks-ru/htmlcss-20210812_vadim992 pull request #17
Opened 2021-09-10 11:38 UTC by vadimkozin

Добавил группу чекбоксов. Нужна подсказка. Всё вроде работает. По табам всё ходит, по пробелу - устанавливает галочку и также снимает. Если мышкой - то щелчки по  label работают как надо. А вот если щелчки мышкой по квадратику - то работает наполовину. Если установить, например, все три галочки, а затем щёлкнуть по средней, то снимется не средняя, а последняя. Щёлкнуть еще раз - снизится средняя.

2021-09-10 11:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-10 18:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-10 18:08 UTC, vadimkozin commented
Добавил одинаковое name и разные value для группы чекбоксов. Но ничего не изменилось. Проблема осталась.

2021-09-12 18:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-12 18:34 UTC, vadimkozin commented
Сдаю на проверку checkbox.

2021-09-13 07:52 UTC, GSemikozov requested changes

2021-09-13 07:52 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +/* this outline around checkbox */
outline же можно добавить через свойство outline?

2021-09-13 12:22 UTC, vadimkozin commented on 07-lection5/01-checkbox/checkbox.css
> +/* this outline around checkbox */
Да можно, только работает это плохо. В Хроме рисует прямые углы. В Файрефокс всё хорошо. В  Сафари ничего не рисует. Правду у меня версия 14.0.3. Может уже и всё хорошо в новой версии. Вот поэтому и делал outline искусственным способом. В результате. Закомментировал свою придумку с outline, написал ниже родной outline.

2021-09-13 14:56 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +/* this outline around checkbox */
Если работает не везде, то можно использовать box-shadow вместо outline - что будет гораздо проще и лучше чем сложный :after ;)

2021-09-13 17:45 UTC, vadimkozin commented on 07-lection5/01-checkbox/checkbox.css
> +/* this outline around checkbox */
Переделал на box-shadow. Можно проверять.

2021-09-13 19:37 UTC, vadimkozin commented
Удалил код под комментами. Можно проверять.

2021-09-14 08:37 UTC, GSemikozov approved these changes

2021-09-14 08:37 UTC, merged