Added dz7-radio
js-tasks-ru/htmlcss-20210812_vadim992 pull request #18
Opened 2021-09-12 18:36 UTC by vadimkozin

Сдаю на проверку radio.

2021-09-12 18:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-13 07:55 UTC, GSemikozov requested changes

2021-09-13 07:55 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +.radio__input:not(:disabled):not(.radio_disabled):checked + .radio__label::after {
здесь всё дублируем, хотя - достаточно указать лишь изменяемые свойства

2021-09-13 12:59 UTC, vadimkozin commented on 07-lection5/02-radio/radio.css
> +.radio__input:not(:disabled):not(.radio_disabled):checked + .radio__label::after {
Удалил несколько строчек. Работоспособность кода осталась. Можно проверять.

2021-09-13 14:56 UTC, GSemikozov approved these changes

2021-09-13 14:57 UTC, merged