dz7-input
js-tasks-ru/htmlcss-20210812_vadim992 pull request #20
Opened 2021-09-13 19:30 UTC by vadimkozin

Добавил Поле ввода. Можно проверять.

2021-09-13 19:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-13 19:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-14 11:26 UTC, GSemikozov requested changes

2021-09-14 11:26 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.input__input {
семантически не очень корректно использовать одно и то же имя для блока и для элемента - предлагаю переименовать в `__control`

2021-09-16 10:41 UTC, vadimkozin commented
Запушил к ключём --force ! Вроде Гит принял. Можно проверять.

2021-09-16 12:55 UTC, GSemikozov approved these changes

2021-09-16 12:56 UTC, merged