Added tabs
js-tasks-ru/htmlcss-20210812_vadim992 pull request #21
Opened 2021-09-14 10:38 UTC by vadimkozin

Добавил tabs-компонент. Можно проверять.

2021-09-14 10:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-14 11:28 UTC, GSemikozov requested changes

2021-09-14 11:28 UTC, GSemikozov commented on 07-lection5/05-tabs/tabs.css
> +  overflow: scroll;
корректнее использовать `overflow-x`

2021-09-14 11:28 UTC, GSemikozov commented on 07-lection5/05-tabs/tabs.css
> +  border-bottom: 1px dotted var(--grey-2);
в дизайне такого dotted бордера нет)

2021-09-14 11:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-09-16 10:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-16 12:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-16 12:26 UTC, vadimkozin commented on 07-lection5/05-tabs/tabs.css
> +  overflow: scroll;
Да. Поправил.

2021-09-16 12:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-09-16 12:34 UTC, vadimkozin commented on 07-lection5/05-tabs/tabs.css
> +  border-bottom: 1px dotted var(--grey-2);
Заменил на solid.

2021-09-16 12:56 UTC, GSemikozov approved these changes

2021-09-16 12:56 UTC, merged