dz4-mainpage
js-tasks-ru/htmlcss-20210812_vadim992 pull request #6
Opened 2021-08-22 07:57 UTC by vadimkozin

1) Добавил в header logo и навигацию. Кнопки sun, toggle, moon оставил на будущее и заменил пока на текст controls
2) Добавил пустые карточки в main-секцию
3) В main секции добавил класс .main, что логично. Но тогда стало два файла main.css (первый уже был изначально с css-переменными). Какой файл лучше переименовать?

2021-08-22 07:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-23 11:26 UTC, GSemikozov commented
> 1. Добавил в header logo и навигацию. Кнопки sun, toggle, moon оставил на будущее и заменил пока на текст controls
> 2. Добавил пустые карточки в main-секцию
> 3. В main секции добавил класс .main, что логично. Но тогда стало два файла main.css (первый уже был изначально с css-переменными). Какой файл лучше переименовать?

3. переименовать можно главный main в index.css

2021-08-23 11:30 UTC, GSemikozov requested changes

2021-08-23 11:30 UTC, GSemikozov commented on components/header/header.css
> +  padding-top: 25px;
лучше на уровне блока .header задать паддинг сверху

2021-08-23 11:30 UTC, GSemikozov commented on components/menu/menu.css
> +  font-family: Inter;
все что касается оформления текста можно унести в .menu__item

2021-08-23 11:30 UTC, GSemikozov commented on components/menu/menu.css
> +.menu__item:nth-child(n+2) {
это лишнее (первый айтем черный потому, что он активный, то есть у него есть класс-модификатор .menu__item_active)

2021-08-23 11:30 UTC, GSemikozov commented on components/nav/nav.css
> +.nav__spacer {
не совсем понял зачем так делать

2021-08-23 11:30 UTC, GSemikozov commented on components/preview/preview.css
> +  padding-top: 68px;
вот эти паддинги это скорее внутренние отступы .main, чем .preview. Но если решим оставить как есть - тоже ок.

2021-08-23 11:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-23 11:58 UTC, vadimkozin commented
Всё поправил. Можно проверять.

2021-08-23 14:42 UTC, vadimkozin commented on components/header/header.css
> +  padding-top: 25px;
Сделал.

2021-08-23 15:16 UTC, vadimkozin commented on components/menu/menu.css
> +  font-family: Inter;
Перенёс в .menu__item. А идея была - в главном писать font-family, а в потомках наследовать. Но, с другой стороны у menu все потомки в .menu__item.

2021-08-23 15:17 UTC, vadimkozin commented on components/nav/nav.css
> +.nav__spacer {
Убрал и заменил паддингом у следующего элемента.

2021-08-23 15:18 UTC, vadimkozin commented on components/preview/preview.css
> +  padding-top: 68px;
Перенёс отступы в .main

2021-08-23 15:41 UTC, GSemikozov approved these changes

2021-08-23 15:41 UTC, merged