added Skeleton
js-tasks-ru/htmlcss-20210812_vadim992 pull request #7
Opened 2021-08-23 16:18 UTC by vadimkozin

Добавил Скелетон. Можно проверять.

2021-08-23 16:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-23 16:24 UTC, GSemikozov requested changes

2021-08-23 16:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 576px;
фиксированные размеры сразу убираем) 
ширину, разве что, по желанию можно ограничить через max-width

2021-08-23 16:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  padding-top: 24px;
padding-right видимо тоже нужен. Проще записать в сокращенной форме padding: 24px 24px 32px;

2021-08-23 16:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  padding-bottom: 24px;
если определяем поведение относительно других внешних элементов - то это марджин

2021-08-23 16:24 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 176px;
ширину лучше задать сразу в процентах, чтобы линии были резиновыми (тянулись или сжимались при сужении или расширении экрана и соответственно увеличении или уменьшении самого компонента)

2021-08-23 20:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-23 20:15 UTC, vadimkozin commented on 04-lection2/02-skeleton/skeleton.css
> +  padding-bottom: 24px;
Решил через gap у родителя flex

2021-08-23 20:15 UTC, vadimkozin commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 176px;
Задал ширину в %

2021-08-23 20:16 UTC, vadimkozin commented
Все комменты поправил. Можно проверять

2021-08-24 06:21 UTC, vadimkozin commented on 04-lection2/02-skeleton/skeleton.css
> +  width: 576px;
Убрал

2021-08-24 06:21 UTC, vadimkozin commented on 04-lection2/02-skeleton/skeleton.css
> +  padding-top: 24px;
Добавил

2021-08-25 16:27 UTC, GSemikozov approved these changes

2021-08-25 16:27 UTC, merged